- name: docker ~> Ensure older version uninstalled
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: docker ~> Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: docker ~> Add Docker apt key.
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: docker ~> Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: docker ~> Add Docker apt key (alternative for older systems without SNI).
  shell: >
    set -o pipefail
    curl -sSL {{ docker_apt_gpg_key }} | sudo apt-key add -
  args:
    warn: false
  when: add_repository_key is failed
  failed_when: false

- name: docker ~> Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: docker ~> install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: docker ~> add {{ docker_user }} to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: docker ~> check docker-compose stat
  stat:
    path: /usr/local/bin/docker-compose
  changed_when: false
  failed_when: false
  register: _docker_compose_path

- name: docker ~> install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"
  when: false == _docker_compose_path.stat.exists
