- name: group ~> ensure group {{ zeus_group }} exists
  group:
    name: "{{ zeus_group }}"
    state: present

- name: user ~> ensure user {{ zeus_user }} exists
  user:
    name: "{{ zeus_user }}"
    state: present
    group: "{{ zeus_group }}"
    create_home: true
    home: "{{ zeus_home }}"
    shell: "/usr/bin/bash"
